name: Release preaparation
on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:

  build-and-pack:
    name: Build and pack
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: echo
      run: echo '{"catalin:da"}' > da.json
    - name: jq
      run: jq -r '.catalin' da.json

